import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./global_Component/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dev Sabbir",
  description: "Generated by sabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="flex w-[1320px] h-screen m-auto">
          <SideBar/>
          {children}

        </div>
      </body>
    </html>
  );
}
